// THE GIFT HEIST — Global Design System
// All components import from here. Never hardcode colors or fonts elsewhere.

export const THEME = {
  colors: {
    void: '#06040A',
    ink: '#0D0A12',
    shadow: '#13101A',
    dusk: '#1C1828',
    borderFaint: '#2A2438',
    borderMid: '#3D3550',
    borderBright: '#5A4E70',
    goldDim: '#6B5A2E',
    goldMid: '#C49A3C',
    gold: '#E8B84B',
    goldBright: '#F5D06A',
    textPrimary: '#EDE0C8',
    textSecondary: '#A89880',
    textMuted: '#6B5E4E',
    pearl: '#F0EDE8',
    sapphire: '#4A9FE8',
    emerald: '#3DCB7A',
    ruby: '#E84A6A',
    diamond: '#B8E8FF',
    success: '#3DCB7A',
    danger: '#E84A6A',
    warning: '#E8B84B',
    info: '#4A9FE8',
  },
  fonts: {
    display: "'Special Elite', cursive",
    body: "'Lora', serif",
    mono: "'Courier New', monospace",
  },
  cityColors: {
    new_cavendish: '#E8B84B',
    shadowport: '#4A9FE8',
    ironhollow: '#E84A6A',
    verenthia: '#B8E8FF',
  },
  jewels: {
    pearl:    { emoji: '🤍', label: 'Pearl',    color: '#F0EDE8', rarity: 'Common',    city: 'New Cavendish' },
    sapphire: { emoji: '💙', label: 'Sapphire', color: '#4A9FE8', rarity: 'Uncommon',  city: 'New Cavendish / Shadowport' },
    emerald:  { emoji: '💚', label: 'Emerald',  color: '#3DCB7A', rarity: 'Rare',      city: 'Shadowport / Ironhollow' },
    ruby:     { emoji: '❤️', label: 'Ruby',     color: '#E84A6A', rarity: 'Epic',      city: 'Ironhollow / Verenthia' },
    diamond:  { emoji: '💎', label: 'Diamond',  color: '#B8E8FF', rarity: 'Legendary', city: 'Verenthia' },
  },
  space: { xs: 4, sm: 8, md: 16, lg: 24, xl: 32, xxl: 48 },
  radius: { sm: 4, md: 8, lg: 16, pill: 999 },
  shadows: {
    card: '0 4px 24px rgba(0,0,0,0.6)',
    gold: '0 0 20px rgba(232,184,75,0.15)',
    jewel: '0 0 16px rgba(255,255,255,0.1)',
  },
} as const;

export const S = {
  page: {
    minHeight: '100vh',
    background: THEME.colors.void,
    fontFamily: THEME.fonts.mono,
    color: THEME.colors.textPrimary,
    overflowX: 'hidden' as const,
    paddingBottom: 72,
  },
  card: {
    background: THEME.colors.ink,
    border: `1px solid ${THEME.colors.borderFaint}`,
    borderRadius: THEME.radius.md,
    padding: THEME.space.lg,
  },
  eyebrow: {
    fontSize: 10,
    letterSpacing: 4,
    textTransform: 'uppercase' as const,
    color: THEME.colors.textMuted,
    fontFamily: THEME.fonts.display,
    marginBottom: THEME.space.sm,
  },
  h1: {
    fontSize: 28,
    fontFamily: THEME.fonts.display,
    color: THEME.colors.textPrimary,
    letterSpacing: 2,
    textTransform: 'uppercase' as const,
    lineHeight: 1.1,
  },
  btnPrimary: {
    background: THEME.colors.gold,
    color: THEME.colors.void,
    border: 'none',
    borderRadius: THEME.radius.sm,
    padding: '14px 28px',
    fontFamily: THEME.fonts.display,
    fontSize: 13,
    fontWeight: 700,
    letterSpacing: 3,
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    width: '100%',
  },
  btnGhost: {
    background: 'transparent',
    color: THEME.colors.textMuted,
    border: `1px solid ${THEME.colors.borderFaint}`,
    borderRadius: THEME.radius.sm,
    padding: '12px 24px',
    fontFamily: THEME.fonts.display,
    fontSize: 11,
    letterSpacing: 2,
    textTransform: 'uppercase' as const,
    cursor: 'pointer',
    width: '100%',
  },
  divider: {
    height: 1,
    background: THEME.colors.borderFaint,
    margin: `${THEME.space.lg}px 0`,
  },
} as const;
